#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct KnownSassOpcode {
    pub opcode: &'static str,
    pub architectures: &'static [&'static str],
    pub class: &'static str,
    pub kind: &'static str,
    pub source: &'static str,
}

pub fn known_sass_opcodes() -> &'static [KnownSassOpcode] {
    KNOWN_SASS_OPCODES
}

const NVIDIA_BINARY_UTILITIES: &str = "nvidia-cuda-binary-utilities-instruction-reference";

const KNOWN_SASS_OPCODES: &[KnownSassOpcode] = &[
    KnownSassOpcode {
        opcode: "BGMMA",
        architectures: &["sm90"],
        class: "tensor-core",
        kind: "warpgroup-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "BMMA",
        architectures: &["sm80", "sm86", "sm89", "sm90"],
        class: "tensor-core",
        kind: "bit-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "DMMA",
        architectures: &["sm100", "sm120"],
        class: "tensor-core",
        kind: "fp64-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "HGMMA",
        architectures: &["sm90"],
        class: "tensor-core",
        kind: "warpgroup-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "HMMA",
        architectures: &["sm80", "sm86", "sm89", "sm90", "sm100", "sm120"],
        class: "tensor-core",
        kind: "half-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "IGMMA",
        architectures: &["sm90"],
        class: "tensor-core",
        kind: "warpgroup-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "IMMA",
        architectures: &["sm80", "sm86", "sm89", "sm90", "sm100", "sm120"],
        class: "tensor-core",
        kind: "integer-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "OMMA",
        architectures: &["sm100", "sm120"],
        class: "tensor-core",
        kind: "fp4-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "QGMMA",
        architectures: &["sm90"],
        class: "tensor-core",
        kind: "warpgroup-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "QMMA",
        architectures: &["sm100", "sm120"],
        class: "tensor-core",
        kind: "fp8-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "LDT",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "tensor-load",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "LDTM",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "tensor-load-matrix",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "STT",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "tensor-store",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "STTM",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "tensor-store-matrix",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UBLKCP",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "bulk-copy",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UBLKPF",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "bulk-prefetch",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UBLKRED",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "bulk-reduce",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UTCHMMA",
        architectures: &["sm100", "sm120"],
        class: "tensor-core",
        kind: "uniform-half-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UTCIMMA",
        architectures: &["sm100", "sm120"],
        class: "tensor-core",
        kind: "uniform-integer-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UTCOMMA",
        architectures: &["sm100", "sm120"],
        class: "tensor-core",
        kind: "uniform-fp4-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UTCQMMA",
        architectures: &["sm100", "sm120"],
        class: "tensor-core",
        kind: "uniform-fp8-mma",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UTMALDG",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "tensor-memory-load-global",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UTMAPF",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "tensor-memory-prefetch",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UTMAREDG",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "tensor-memory-reduce-global",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "UTMASTG",
        architectures: &["sm100", "sm120"],
        class: "tensor-memory",
        kind: "tensor-memory-store-global",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "WARPGROUP",
        architectures: &["sm90"],
        class: "warpgroup",
        kind: "warpgroup-control",
        source: NVIDIA_BINARY_UTILITIES,
    },
    KnownSassOpcode {
        opcode: "WARPGROUPSET",
        architectures: &["sm90"],
        class: "warpgroup",
        kind: "warpgroup-control",
        source: NVIDIA_BINARY_UTILITIES,
    },
];
