[package]
name = "nn-rust-inference"
version = "0.1.0"
edition = "2024"

[dependencies]
cuda-device = { git = "https://github.com/NVlabs/cuda-oxide.git", tag = "v0.1.0" }
cuda-core = { git = "https://github.com/NVlabs/cuda-oxide.git", tag = "v0.1.0" }
cuda-host = { git = "https://github.com/NVlabs/cuda-oxide.git", tag = "v0.1.0" }
cuda-bindings = { git = "https://github.com/NVlabs/cuda-oxide.git", tag = "v0.1.0" }
nn-rust-profiling = { path = "../profiling" }
serde_json = "1.0.150"
